DELETE SMXREF;
--##TTU
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('FLAG1', 'FLAG2', 'FLAG3', 'FLAG4');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('PA', 'PB', 'PC');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('QA', 'QB', 'QC');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('VOLTMAGA', 'VOLTMAGB', 'VOLTMAGC');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('LOCKFLAG1');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('AMPA');
--INSERT INTO SMXREF SELECT 'LOAD', 'B5934HE05T01', 'AMPA', 2, 114, 'R', 25, 'CV' FROM DUAL;

--##METER
INSERT INTO SMXREF
SELECT 'METER', REGEXP_SUBSTR(DEVICE_TYPE,'\w+',1,1), REGEXP_SUBSTR(DEVICE_TYPE,'\w+',1,2), 1, 
        STN_NUM, CATEGORY, REC_NUM, 'CS'
FROM DDS_STATUS WHERE DEVICE_TYPE LIKE 'WT%' ;
COMMIT;

INSERT INTO SMXREF
SELECT 'METER', REGEXP_SUBSTR(TELEMETRY_TYPE,'\w+',1,1), REGEXP_SUBSTR(TELEMETRY_TYPE,'\w+',1,2), 2, 
        STN_NUM, CATEGORY, REC_NUM, 'CV'
FROM DDS_TELEMETRY WHERE TELEMETRY_TYPE LIKE 'WT%';
COMMIT;


--##FCI
/*DELETE DAS_RTDB@DASMAP WHERE EQUIP_NUM IN (SELECT NAME FROM VIEW_ELECTRIC_CONN@DASMAP WHERE BLOCKNAME LIKE '%-M%' AND FSC IN (108, 110, 114));

INSERT INTO DAS_RTDB@DASMAP
SELECT 'SWITCH', REGEXP_SUBSTR(DEVICE_TYPE,'\w+',1,1), REGEXP_SUBSTR(DEVICE_TYPE,'\w+',1,2), 0, 1, 1, 
        STN_NUM, CATEGORY, REC_NUM, 'CS', REGEXP_SUBSTR(DEVICE_TYPE,'\w+',1,2), 
        'SWITCH'||' '||REGEXP_SUBSTR(DEVICE_TYPE,'\w+',1,1)||' '|| REGEXP_SUBSTR(DEVICE_TYPE,'\w+',1,2), NULL
FROM DDS_STATUS WHERE DEVICE_TYPE LIKE '%FI%:%' AND REPLACE(REGEXP_SUBSTR(DEVICE_TYPE,'\w+',1,1), 'FI', 'S') IN 
    (SELECT NAME FROM VIEW_ELECTRIC_CONN@DASMAP WHERE BLOCKNAME LIKE '%-M%' AND FSC IN (108, 110, 114));
COMMIT;

INSERT INTO DAS_RTDB@DASMAP
SELECT 'SWITCH', REGEXP_SUBSTR(TELEMETRY_TYPE,'\w+',1,1), REGEXP_SUBSTR(TELEMETRY_TYPE,'\w+',1,2), 0, 1, 2, 
        STN_NUM, CATEGORY, REC_NUM, 'CS', REGEXP_SUBSTR(TELEMETRY_TYPE,'\w+',1,2), 
        'SWITCH'||' '||REGEXP_SUBSTR(TELEMETRY_TYPE,'\w+',1,1)||' '|| REGEXP_SUBSTR(TELEMETRY_TYPE,'\w+',1,2), NULL
FROM DDS_TELEMETRY WHERE TELEMETRY_TYPE LIKE '%FI%:%' AND REPLACE(REGEXP_SUBSTR(TELEMETRY_TYPE,'\w+',1,1), 'FI', 'S') IN 
    (SELECT NAME FROM VIEW_ELECTRIC_CONN@DASMAP WHERE BLOCKNAME LIKE '%-M%' AND FSC IN (108, 110, 114));
COMMIT;


UPDATE DAS_RTDB SET EQUIP_NUM = REPLACE(EQUIP_NUM, 'FI', 'S'), DESCRIPT =  REPLACE(DESCRIPT, 'FI', 'S') WHERE EQUIP_NUM LIKE '%FI%'
AND  REPLACE(EQUIP_NUM, 'FI', 'S') IN (SELECT NAME FROM VIEW_ELECTRIC_CONN@DASMAP WHERE BLOCKNAME LIKE '%-M%' AND FSC IN (108, 110, 114));*/




COMMIT;
