DROP TABLE INTF_MDMS_DATA;
CREATE TABLE INTF_MDMS_DATA 
    ("METER" VARCHAR2(11) NOT NULL, 
     "METERUNIQUEID" VARCHAR2(10) NOT NULL, 
     "P_KWH" VARCHAR2(6), 
     "P_KQH_P" VARCHAR2(6), 
     "P_KQH_M" VARCHAR2(6), 
     "S_KWH" VARCHAR2(6),
     "S_KQH_P" VARCHAR2(6),
     "S_KQH_M" VARCHAR2(6),
     "P_KW" VARCHAR2(6), 
     "P_KQ_P" VARCHAR2(6), 
     "P_KQ_M" VARCHAR2(6), 
     "S_KW" VARCHAR2(6), 
     "S_KQ_P" VARCHAR2(6), 
     "S_KQ_M" VARCHAR2(6), 
     "READINGTIME" DATE NOT NULL, 
     "RECEIVETIME" DATE NOT NULL, 
     CONSTRAINT "INTF_MDMS_DATA_PK" PRIMARY KEY("METER", "METERUNIQUEID", "READINGTIME") USING INDEX );


EXIT;

