DROP TABLE MDMS_METER;
CREATE TABLE MDMS_METER 
(
    EQUIP_NUM VARCHAR2(19), 
    COLNAME VARCHAR2(19),
    NAMEID VARCHAR2(10),
    SEQ_ID NUMBER(10),
    VALUE_RT NUMBER(10,3),
    DataTime Date
);

EXIT;