
--#######################################DEV#######################################--
-- DROP TABLE MDMS_METER_POOL;
-- CREATE TABLE MDMS_METER_POOL
-- (
--     EQUIP_NUM VARCHAR2(19), 
--     COLNAME VARCHAR2(19),
--     METER_NAME VARCHAR2(12),
--     SEQ_ID NUMBER(10),
--     VALUE_RT NUMBER(10,3),
--     DATATIME DATE
-- );

DROP TABLE MDMS_METER_DATA;
CREATE TABLE MDMS_METER_DATA
(
    TTU_NAME VARCHAR2(63),
    METER_NAME VARCHAR2(12),
    PA NUMBER,
    AMPA NUMBER,
    LOCKFLAG2 NUMBER,
    EFLAG NUMBER(4)
);


CREATE INDEX MDMS_METER_DATA_IDX1 ON MDMS_METER_DATA (METER_NAME);


--#SET SERVEROUTPUT ON

CREATE OR REPLACE TRIGGER TRI_PROCESSING_METER_DATA AFTER INSERT ON MDMS_METER
FOR EACH ROW
BEGIN
    IF :NEW.COLNAME = 'PA' THEN
        UPDATE MDMS_METER_DATA SET PA = :NEW.VALUE_RT WHERE METER_NAME = :NEW.NAMEID;
    ELSIF :NEW.COLNAME = 'AMPA' THEN
        UPDATE MDMS_METER_DATA SET AMPA = :NEW.VALUE_RT WHERE METER_NAME = :NEW.NAMEID;
    ELSIF :NEW.COLNAME = 'LOCKFLAG2' THEN
        UPDATE MDMS_METER_DATA SET LOCKFLAG2 = :NEW.VALUE_RT WHERE METER_NAME = :NEW.NAMEID;
    ELSE
        UPDATE MDMS_METER_DATA SET EFLAG = :NEW.VALUE_RT WHERE METER_NAME = :NEW.NAMEID;
    END IF;
END;
/

CREATE OR REPLACE VIEW VIEW_METERSUM AS 
SELECT TTU_NAME, SUM(PA) P, SUM(AMPA) AMP, SUM(LOCKFLAG2) LOCKFLAG2, COUNT(*) METERCNT FROM MDMS_METER_DATA GROUP BY TTU_NAME;



EXIT;