DROP TABLE SMXREF;
CREATE TABLE SMXREF
(
    TABLENAME         VARCHAR2(19) NOT NULL,
    EQUIP_NUM         VARCHAR2(19) NOT NULL,
    COLNAME           VARCHAR2(19) NOT NULL,
    RTDBTYPE          NUMBER(1),
    STATION           NUMBER(6),
    CATEGORY          CHAR(1),
    POINT             NUMBER(6),
    ATTRIBUTE         CHAR(2)
);

--##TTU
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('FLAG1', 'FLAG2', 'FLAG3', 'FLAG4');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('PA', 'PB', 'PC');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('QA', 'QB', 'QC');
--INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('VOLTMAGA', 'VOLTMAGB', 'VOLTMAGC');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('LFA', 'LFB', 'LFC');
--INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('AMPA');
COMMIT;

--##FCI_TTU
CREATE OR REPLACE VIEW FCI_TTU_INFO AS SELECT MAIN.NAME, MAIN.FEEDER1, MAIN.FEEDER2, MAIN.FSC,
       STATION_FAULTFLAGA, CATEGORY_FAULTFLAGA, POINT_FAULTFLAGA, RTDBTYPE_FAULTFLAGA, ATTRIBUTE_FAULTFLAGA,
       STATION_FAULTFLAGB, CATEGORY_FAULTFLAGB, POINT_FAULTFLAGB, RTDBTYPE_FAULTFLAGB, ATTRIBUTE_FAULTFLAGB,
       STATION_FAULTFLAGC, CATEGORY_FAULTFLAGC, POINT_FAULTFLAGC, RTDBTYPE_FAULTFLAGC, ATTRIBUTE_FAULTFLAGC,
       STATION_AMPA, CATEGORY_AMPA, POINT_AMPA, RTDBTYPE_AMPA, ATTRIBUTE_AMPA,
       STATION_AMPB, CATEGORY_AMPB, POINT_AMPB, RTDBTYPE_AMPB, ATTRIBUTE_AMPB,
       STATION_AMPC, CATEGORY_AMPC, POINT_AMPC, RTDBTYPE_AMPC, ATTRIBUTE_AMPC,
       STATION_VOLTMAGA, CATEGORY_VOLTMAGA, POINT_VOLTMAGA, RTDBTYPE_VOLTMAGA, ATTRIBUTE_VOLTMAGA,
       STATION_VOLTMAGB, CATEGORY_VOLTMAGB, POINT_VOLTMAGB, RTDBTYPE_VOLTMAGB, ATTRIBUTE_VOLTMAGB,
       STATION_VOLTMAGC, CATEGORY_VOLTMAGC, POINT_VOLTMAGC, RTDBTYPE_VOLTMAGC, ATTRIBUTE_VOLTMAGC,
       STATION_PA, CATEGORY_PA, POINT_PA, RTDBTYPE_PA, ATTRIBUTE_PA,
       STATION_PB, CATEGORY_PB, POINT_PB, RTDBTYPE_PB, ATTRIBUTE_PB,
       STATION_PC, CATEGORY_PC, POINT_PC, RTDBTYPE_PC, ATTRIBUTE_PC,
       STATION_QA, CATEGORY_QA, POINT_QA, RTDBTYPE_QA, ATTRIBUTE_QA,
       STATION_QB, CATEGORY_QB, POINT_QB, RTDBTYPE_QB, ATTRIBUTE_QB,
       STATION_QC, CATEGORY_QC, POINT_QC, RTDBTYPE_QC, ATTRIBUTE_QC FROM (
            SELECT OBJ.KEYIDX, TP.NAME, TP.FEEDER1, TP.FEEDER2, TP.FSC FROM TB_TP TP
                --## R -> P
            LEFT JOIN (SELECT IX.KEYIDX, NAME FROM SWITCHPARAM SP, INPUTXREF IX WHERE SP.IDX = IX.KEYIDX AND IX.TABLENAME = 'SWITCHINPUT'
                    UNION SELECT IX.KEYIDX, NAME FROM LOADPARAM LP,   INPUTXREF IX WHERE LP.IDX = IX.KEYIDX AND IX.TABLENAME = 'LOADINPUT') OBJ
            ON TP.NAME = OBJ.NAME
        ) MAIN
LEFT JOIN (SELECT KEYIDX, STATION STATION_FAULTFLAGA, CATEGORY CATEGORY_FAULTFLAGA, POINT POINT_FAULTFLAGA, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_FAULTFLAGA, ATTRIBUTE ATTRIBUTE_FAULTFLAGA FROM INPUTXREF
           WHERE COLNAME = 'FAULTFLAGA') FFA
ON MAIN.KEYIDX = FFA.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_FAULTFLAGB, CATEGORY CATEGORY_FAULTFLAGB, POINT POINT_FAULTFLAGB, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_FAULTFLAGB, ATTRIBUTE ATTRIBUTE_FAULTFLAGB FROM INPUTXREF
           WHERE COLNAME = 'FAULTFLAGB') FFB
ON MAIN.KEYIDX = FFB.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_FAULTFLAGC, CATEGORY CATEGORY_FAULTFLAGC, POINT POINT_FAULTFLAGC, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_FAULTFLAGC, ATTRIBUTE ATTRIBUTE_FAULTFLAGC FROM INPUTXREF
           WHERE COLNAME = 'FAULTFLAGC') FFC
ON MAIN.KEYIDX = FFC.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_AMPA, CATEGORY CATEGORY_AMPA, POINT POINT_AMPA, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_AMPA, ATTRIBUTE ATTRIBUTE_AMPA FROM INPUTXREF
           WHERE COLNAME = 'AMPA') IA
ON MAIN.KEYIDX = IA.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_AMPB, CATEGORY CATEGORY_AMPB, POINT POINT_AMPB, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_AMPB, ATTRIBUTE ATTRIBUTE_AMPB FROM INPUTXREF
           WHERE COLNAME = 'AMPB') IB
ON MAIN.KEYIDX = IB.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_AMPC, CATEGORY CATEGORY_AMPC, POINT POINT_AMPC, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_AMPC, ATTRIBUTE ATTRIBUTE_AMPC FROM INPUTXREF
           WHERE COLNAME = 'AMPC') IC
ON MAIN.KEYIDX = IC.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_VOLTMAGA, CATEGORY CATEGORY_VOLTMAGA, POINT POINT_VOLTMAGA, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_VOLTMAGA, ATTRIBUTE ATTRIBUTE_VOLTMAGA FROM INPUTXREF
           WHERE COLNAME = 'VOLTMAGA') VA
ON MAIN.KEYIDX = VA.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_VOLTMAGB, CATEGORY CATEGORY_VOLTMAGB, POINT POINT_VOLTMAGB, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_VOLTMAGB, ATTRIBUTE ATTRIBUTE_VOLTMAGB FROM INPUTXREF
           WHERE COLNAME = 'VOLTMAGB') VB
ON MAIN.KEYIDX = VB.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_VOLTMAGC, CATEGORY CATEGORY_VOLTMAGC, POINT POINT_VOLTMAGC, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_VOLTMAGC, ATTRIBUTE ATTRIBUTE_VOLTMAGC FROM INPUTXREF
           WHERE COLNAME = 'VOLTMAGC') VC
ON MAIN.KEYIDX = VC.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_PA, CATEGORY CATEGORY_PA, POINT POINT_PA, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_PA, ATTRIBUTE ATTRIBUTE_PA FROM INPUTXREF
           WHERE COLNAME = 'PA') PA
ON MAIN.KEYIDX = PA.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_PB, CATEGORY CATEGORY_PB, POINT POINT_PB, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_PB, ATTRIBUTE ATTRIBUTE_PB FROM INPUTXREF
           WHERE COLNAME = 'PB') PB
ON MAIN.KEYIDX = PB.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_PC, CATEGORY CATEGORY_PC, POINT POINT_PC, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_PC, ATTRIBUTE ATTRIBUTE_PC FROM INPUTXREF
           WHERE COLNAME = 'PC') PC
ON MAIN.KEYIDX = PC.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_QA, CATEGORY CATEGORY_QA, POINT POINT_QA, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_QA, ATTRIBUTE ATTRIBUTE_QA FROM INPUTXREF
           WHERE COLNAME = 'QA') QA
ON MAIN.KEYIDX = QA.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_QB, CATEGORY CATEGORY_QB, POINT POINT_QB, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_QB, ATTRIBUTE ATTRIBUTE_QB FROM INPUTXREF
           WHERE COLNAME = 'QB') QB
ON MAIN.KEYIDX = QB.KEYIDX
LEFT JOIN (SELECT KEYIDX, STATION STATION_QC, CATEGORY CATEGORY_QC, POINT POINT_QC, DECODE(RTDBTYPE, 1, 'S', 2, 'T', NULL) RTDBTYPE_QC, ATTRIBUTE ATTRIBUTE_QC FROM INPUTXREF
           WHERE COLNAME = 'QC') QC
ON MAIN.KEYIDX = QC.KEYIDX


EXIT;

