DROP TABLE SMXREF;
CREATE TABLE SMXREF
(
    TABLENAME         VARCHAR2(19) NOT NULL,
    EQUIP_NUM         VARCHAR2(19) NOT NULL,
    COLNAME           VARCHAR2(19) NOT NULL,
    RTDBTYPE          NUMBER(1),
    STATION           NUMBER(6),
    CATEGORY          CHAR(1),
    POINT             NUMBER(6),
    ATTRIBUTE         CHAR(2)
);

--##TTU
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('FLAG1', 'FLAG2', 'FLAG3', 'FLAG4');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('PA', 'PB', 'PC');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('QA', 'QB', 'QC');
--INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('VOLTMAGA', 'VOLTMAGB', 'VOLTMAGC');
INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('LFA', 'LFB', 'LFC');
--INSERT INTO SMXREF SELECT TABLENAME, EQUIP_NUM, COLNAME, RTDBTYPE, STATION, CATEGORY, POINT, ATTRIBUTE FROM DAS_RTDB@DASMAP WHERE TABLENAME = 'LOAD' AND COLNAME IN ('AMPA');
COMMIT;

--##METER

EXIT;