DROP TABLE SWITCH_TTU;
CREATE TABLE SWITCH_TTU 
(
    SWITCH_NAME VARCHAR2(63) NOT NULL,
    TTU_NAME    VARCHAR2(63) NOT NULL
);

INSERT INTO  SWITCH_TTU SELECT SWITCH_NAME, LOAD_NAME FROM SW_LOAD_LIST@DASMAP;
COMMIT;

EXIT;
