DROP TABLE TTU_METER;
CREATE TABLE TTU_METER
(
     TTU_NAME     VARCHAR2(63) NOT NULL,
     METER_NAME   VARCHAR2(63) NOT NULL
);

INSERT INTO TTU_METER SELECT LOAD_NAME, METER_NAME FROM LOAD_METER_LIST@DASMAP;
COMMIT;

EXIT;
