-- CREATE TABLE GIS_BREAKER_BACKUP as SELECT * FROM GIS_BREAKER;
-- CREATE TABLE GIS_CONDUCTOR_BACKUP as SELECT * FROM GIS_CONDUCTOR;
-- CREATE TABLE GIS_LOADTRANSFORMER_BACKUP as SELECT * FROM GIS_LOADTRANSFORMER;
-- CREATE TABLE GIS_SWITCH_BACKUP as SELECT * FROM GIS_SWITCH;
-- CREATE TABLE GIS_SUBSTATION_BACKUP as SELECT * FROM GIS_SUBSTATION;

TRUNCATE TABLE  GIS_BREAKER;
TRUNCATE TABLE  GIS_CONDUCTOR;
TRUNCATE TABLE  GIS_LOADTRANSFORMER;
TRUNCATE TABLE  GIS_SWITCH;
TRUNCATE TABLE  GIS_SUBSTATION;


INSERT INTO GIS_BREAKER SELECT * FROM GIS_BREAKER_BACKUP;
INSERT INTO GIS_CONDUCTOR SELECT * FROM GIS_CONDUCTOR_BACKUP;
INSERT INTO GIS_LOADTRANSFORMER SELECT * FROM GIS_LOADTRANSFORMER_BACKUP;
INSERT INTO GIS_SWITCH SELECT * FROM GIS_SWITCH_BACKUP;
INSERT INTO GIS_SUBSTATION SELECT * FROM GIS_SUBSTATION_BACKUP;
COMMIT;

EXIT;