CREATE OR REPLACE FUNCTION GET_POINT_MINUTE (R_NUM IN NUMBER , R_DATE IN VARCHAR2, R_INTL IN NUMBER) 
RETURN TABLE_OUTPUT_DATA PIPELINED AS 
-- BACK
DT_B    DATE;
ITVL_B  FLOAT;
-- FRONT
DT_F    DATE;
ITVL_F  FLOAT;
-- CORRECT
HH      VARCHAR2(2);
MM      VARCHAR2(2);
DT      DATE;
VAL     FLOAT;

BEGIN 
    FOR X IN 0 .. 23 LOOP
        FOR Y IN 0 .. ROUND((60/R_INTL),0)-1 LOOP 
            HH:= LPAD(X, 2, '0');
            MM:= LPAD(Y*R_INTL, 2, '0');
        
            -- GET INTERVAL (BACK)
            SELECT  (TO_DATE(R_DATE||HH||MM, 'YYYY-MM-DD HH24:MI:SS')-MAX(READINGDATE)) 
            INTO    ITVL_B 
            FROM    METERDATA 
            WHERE   READING_NUM=R_NUM 
            AND     READINGDATE<=TO_DATE(R_DATE||HH||MM, 'YYYY-MM-DD HH24:MI:SS');


            PIPE ROW(TYPE_OUTPUT_DATA(R_NUM,DT,R_DATE,HH,MM,VAL)); 
        END LOOP;
    END LOOP;
END; 
/ 

SET SERVEROUTPUT ON;
DECLARE
    CURRENT_DATE    VARCHAR2(12);
    CURRENT_HOUR    NUMBER(2);
    PROCESSING_HOUR VARCHAR2(2);
    VAL             NUMBER;
BEGIN
    SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') INTO CURRENT_DATE FROM DUAL;
    SELECT EXTRACT(HOUR FROM CAST(SYSDATE AS TIMESTAMP)) INTO CURRENT_HOUR FROM DUAL;

    FOR HH IN 0 .. CURRENT_HOUR
    LOOP
        PROCESSING_HOUR := LPAD(HH, 2, '0');
        DBMS_OUTPUT.PUT_LINE('PROCESSING HOUR: ' ||PROCESSING_HOUR);
        FOR REC IN (SELECT DISTINCT METER_NAME FROM METERDATA)
        LOOP
            DBMS_OUTPUT.PUT_LINE('PROCESSING METER: ' ||REC.METER_NAME);
            DBMS_OUTPUT.PUT_LINE(TO_DATE(CURRENT_DATE||PROCESSING_HOUR,'YYYY-MM-DD HH24')  );
            DBMS_OUTPUT.PUT_LINE(TO_DATE(CURRENT_DATE||PROCESSING_HOUR||':59:59','YYYY-MM-DD HH24:MI:SS') );
             SELECT VALUE INTO VAL FROM METERDATA 
             WHERE DATATIME BETWEEN TO_DATE(CURRENT_DATE,'YYYY-MM-DD') 
                                 AND TO_DATE(CURRENT_DATE,'YYYY-MM-DD');
            DBMS_OUTPUT.PUT_LINE('PROCESSING VAL: ' ||VAL);
        END LOOP;
    END LOOP;
END;
/