/*################################################################################################################################################## 
--##                  
--##  Purpose:			Following scripts are to trace and find the nearest line of each device
--##                    
--##  Rely on table:   
--##                    "SOURCENODE"        TONODEIDX
--##                    "SWITCHPARAM"       FRNODEIDX, TONODEIDX
--##                    "TRANSFORMERPARAM"  FRNODEIDX, TONODEIDX
--##                    "LINEPARAM"         FRNODEIDX, TONODEIDX
--##                    "OUTPUTXREF"        STATION, CATEGORY, POINT, ATTRIBUTE, RTDBTYPE               
--##                    
--##  Additional notes:	
--##                    1. PROCESSING SPEED 50,000 DEVICE/MIN. (EXCLUDE SOURCENODE AND LINE)
--##                    
--##  Created on:      	2021-11-22 by WK
--##  Last modify:     	2021-11-22 by WK
--##################################################################################################################################################*/

--#Create Trace Table
DROP TABLE SWTUPLINEXREF;
CREATE TABLE SWTUPLINEXREF AS
SELECT 'SOURCENODE'       TABLENAME, NAME, IDX, 1234  FSC, 0 UFID, 0 FRNODEIDX ,NODEIDX TONODEIDX,  0 VST_CTR, 0 UPLINE_IDX FROM SOURCENODEPARAM
UNION
SELECT 'SWITCHINPUT'      TABLENAME, NAME, IDX, 114  FSC, 0 UFID, FRNODEIDX   , TONODEIDX,         0 VST_CTR, 0 UPLINE_IDX FROM SWITCHPARAM
UNION
SELECT 'TRANSFORMERINPUT' TABLENAME, NAME, IDX, 118  FSC, 0 UFID, FRNODEIDX   , TONODEIDX,         0 VST_CTR, 0 UPLINE_IDX FROM TRANSFORMERPARAM
UNION
SELECT 'LINEOUTPUT'       TABLENAME, NAME, IDX, 106  FSC, 0 UFID, FRNODEIDX   , TONODEIDX,         0 VST_CTR, 0 UPLINE_IDX FROM LINEPARAM;
UPDATE SWTUPLINEXREF SET UFID = ROWNUM;
UPDATE SWTUPLINEXREF SET FSC = 801 WHERE FSC = 114 AND IDX IN (SELECT BRKIDX FROM FEEDERPARAM WHERE FDTYPE = 1);
UPDATE SWTUPLINEXREF SET FSC = 881 WHERE FSC = 114 AND IDX IN (SELECT BRKIDX FROM FEEDERPARAM WHERE FDTYPE = 0);
COMMIT;
--#Optimize Performance
CREATE INDEX SWTUPLINEXREF_FRNODEIDX ON SWTUPLINEXREF (FRNODEIDX);
CREATE INDEX SWTUPLINEXREF_TONODEIDX ON SWTUPLINEXREF (TONODEIDX);
CREATE INDEX SWTUPLINEXREF_VST ON SWTUPLINEXREF (VST_CTR);
CREATE INDEX SWTUPLINEXREF_UFID ON SWTUPLINEXREF (UFID);

DECLARE
    VSTCTR NUMBER := 0;
    UPLINEIDX NUMBER := 0;
    PROCEDURE TRACE(INNID IN NUMBER, INUFID IN NUMBER) 
    IS
    BEGIN
        FOR DEV IN (SELECT * FROM SWTUPLINEXREF WHERE (FRNODEIDX = INNID OR TONODEIDX = INNID) AND UFID <> INUFID)
        LOOP
            IF DEV.FSC = 106 THEN
                UPLINEIDX := DEV.IDX;
            END IF;
            SELECT VST_CTR INTO VSTCTR FROM SWTUPLINEXREF WHERE UFID = DEV.UFID;
            VSTCTR := VSTCTR + 1;
            UPDATE SWTUPLINEXREF SET VST_CTR = VSTCTR WHERE UFID = DEV.UFID;
            COMMIT;
            --# PREVENT OBJECT FROM BEING TRACED TWICE
            IF VSTCTR < 2 THEN
                IF DEV.FSC = 881 THEN
                    UPDATE SWTUPLINEXREF SET UPLINE_IDX = UPLINEIDX WHERE UFID = DEV.UFID;
                    CONTINUE;
                ELSE
                    IF DEV.FRNODEIDX = INNID THEN
                        TRACE(DEV.TONODEIDX, DEV.UFID);
                    ELSIF DEV.TONODEIDX = INNID THEN
                        TRACE(DEV.FRNODEIDX, DEV.UFID);
                    ELSE
                        EXIT;
                    END IF;
                END IF;
            END IF;
        END LOOP;
    END TRACE;
BEGIN
    --# Only Got Frnodeid
    FOR SRC IN (SELECT UFID, TONODEIDX FROM SWTUPLINEXREF WHERE FSC = 1234)
    LOOP
        --# Reset!
        TRACE(SRC.TONODEIDX, SRC.UFID);
    END LOOP;
END;
/

--# Remove Line
DELETE SWTUPLINEXREF WHERE FSC <> 881;
COMMIT;
--# Adjust Column
ALTER TABLE SWTUPLINEXREF DROP COLUMN UFID;
ALTER TABLE SWTUPLINEXREF DROP COLUMN FSC;
ALTER TABLE SWTUPLINEXREF DROP COLUMN FRNODEIDX;
ALTER TABLE SWTUPLINEXREF DROP COLUMN TONODEIDX;
ALTER TABLE SWTUPLINEXREF DROP COLUMN VST_CTR;

ALTER TABLE SWTUPLINEXREF ADD (STATION   NUMBER(5));
ALTER TABLE SWTUPLINEXREF ADD (CATEGORY  CHAR(1));
ALTER TABLE SWTUPLINEXREF ADD (POINT     NUMBER(5));
ALTER TABLE SWTUPLINEXREF ADD (ATTRIBUTE VARCHAR2(5));
ALTER TABLE SWTUPLINEXREF ADD (RTDBTYPE  CHAR(1));

--# Merge Line Point
MERGE INTO SWTUPLINEXREF TARGET
USING (SELECT TABLENAME, KEYIDX, STATION, CATEGORY, POINT, ATTRIBUTE, RTDBTYPE FROM OUTPUTXREF OX WHERE TABLENAME = 'LINEOUTPUT' AND COLNAME = 'COLORCODE') SOURCE
ON (TARGET.UPLINE_IDX=SOURCE.KEYIDX)
WHEN MATCHED THEN
UPDATE 
    SET TARGET.STATION=SOURCE.STATION, TARGET.CATEGORY=SOURCE.CATEGORY, TARGET.POINT=SOURCE.POINT, TARGET.ATTRIBUTE=SOURCE.ATTRIBUTE, TARGET.RTDBTYPE=SOURCE.RTDBTYPE;

--# Adjust Column
ALTER TABLE SWTUPLINEXREF DROP COLUMN UPLINE_IDX;
EXIT;

