

--##DASMAP
DELETE DAS_RTDB WHERE TABLENAME = 'UF';
--#4406 XXXX -> 102 R O
INSERT INTO DAS_RTDB SELECT 'UF', 'WA_SFDUF','STASTATUS', 0, 1, 1, 4406, 'P', 1, 'CS', 'STASTATUS', 'WA_SFDUF-STASTATUS', NULL FROM DUAL;
INSERT INTO DAS_RTDB SELECT 'UF', 'WB_SFDUF','STASTATUS', 0, 1, 1, 4406, 'P', 2, 'CS', 'STASTATUS', 'WA_SFDUF-STASTATUS', NULL FROM DUAL;
INSERT INTO DAS_RTDB SELECT 'UF', 'WA_SFDUF','LOCKFLAG', 0, 1, 1, 4407, 'P', 1, 'CS', 'LOCKFLAG', 'WA_SFDUF-LOCKFLAG', NULL FROM DUAL;
INSERT INTO DAS_RTDB SELECT 'UF', 'WB_SFDUF','LOCKFLAG', 0, 1, 1, 4407, 'P', 2, 'CS', 'LOCKFLAG', 'WA_SFDUF-LOCKFLAG', NULL FROM DUAL;

DELETE DAS_RTDB WHERE TABLENAME = 'FEEDER' AND COLNAME IN ('LSGROUPLOCKFLAG', 'LSACT', 'LSLOCKFLAG');
INSERT INTO DAS_RTDB SELECT 'FEEDER', NAME, 'LSGROUPLOCKFLAG', 0, 1, 1, 4409, 'P', COLORCODE, 'CS', 'LSGROUPLOCKFLAG'   , 'LSGROUPLOCKFLAG-' ||NAME, NULL FROM FEEDERPARAM2 ;
INSERT INTO DAS_RTDB SELECT 'FEEDER', NAME, 'LSACT'          , 0, 1, 2, 4410, 'P', COLORCODE, 'CV', 'LSACT'   , 'LSACT-' ||NAME, NULL FROM FEEDERPARAM2 ;
INSERT INTO DAS_RTDB SELECT 'FEEDER', NAME, 'LSLOCKFLAG'     , 0, 1, 1, 4411, 'P', COLORCODE, 'CS', 'LSLOCKFLAG'   , 'LSLOCKFLAG-' ||NAME, NULL FROM FEEDERPARAM2 ;
COMMIT;
--##PRISM
--##LS

DELETE LSSCOPEPARAM;
INSERT INTO LSSCOPEPARAM SELECT 1, 'A' FROM DUAL;
INSERT INTO LSSCOPEPARAM SELECT 2, 'B' FROM DUAL;
COMMIT;

DELETE LSSCOPEINPUT;
INSERT INTO LSSCOPEINPUT SELECT 1, 0, 0 FROM DUAL;
INSERT INTO LSSCOPEINPUT SELECT 2, 0, 0 FROM DUAL;
COMMIT;

-- ## WORKAROUND
UPDATE FEEDERPARAM2 SET LSSCOPEIDX = 1, LSFEEDER_PRIORITY = ROWNUM, LSFDIDX = ROWNUM WHERE SUBSTIDX = 0;
UPDATE FEEDERPARAM2 SET LSSCOPEIDX = 2, LSFEEDER_PRIORITY = ROWNUM, LSFDIDX = (SELECT MAX(LSFDIDX) FROM FEEDERPARAM2) + ROWNUM WHERE SUBSTIDX = 2;
COMMIT;

--## Need Dr.Yan's help ##--
-- UPDATE FEEDERPARAM SET LSSCOPEIDX = 1, LSFEEDER_PRIORITY = ROWNUM, LSFDIDX = ROWNUM WHERE FDTYPE = 0 AND SUBSTIDX = 0;
-- UPDATE FEEDERPARAM SET LSSCOPEIDX = 2, LSFEEDER_PRIORITY = ROWNUM, LSFDIDX = (SELECT MAX(LSFDIDX) FROM FEEDERPARAM) + ROWNUM WHERE FDTYPE = 0 AND SUBSTIDX = 2;


DELETE LS_CONFIGURATION;
INSERT INTO LS_CONFIGURATION (NAME, VALUE, COMMENTS)
    SELECT 'FD_OPEN_DELAY', 10, 'minutes, Waiting time between feeder' FROM DUAL
    UNION
    SELECT 'FD_CLOSE_DELAY', 10, 'minutes, Waiting time between feeder' FROM DUAL
    UNION
    SELECT 'CHECK_P_INTERVAL', 5, 'seconds, Waiting time between area' FROM DUAL
    UNION
    SELECT 'CHECK_AREA_INTERVAL', 15, 'minutes, Waiting time between area' FROM DUAL
    UNION
    SELECT 'USE_REDUCE', 1, 'Using reduce option' FROM DUAL
    UNION
    -- SELECT 'VALIDATE_LOAD_CAPABILITY', 0, 'Using reduce option' FROM DUALre
    -- UNION
    -- SELECT 'ROTATING_MODE', 2, '0: Check p, periodically 1: Rotating anyway, Open Next Area First, periodically 2: Rotating anyway, Open Next Area First, one time.' FROM DUAL
    -- UNION
    -- SELECT 'ALTERNATIVE', 0, '0: close all, open all, 1: close 1 open 1...' FROM DUAL
    -- UNION
    -- SELECT 'KEEP_CEHCKING', 0, '0: meet demand then exit, 1:keep checing until stop the mission' FROM DUAL
    -- UNION
    SELECT 'UF_CHECK_INTERVAL', 5, 'seconds, Waiting time between check' FROM DUAL
    UNION
    SELECT 'UF_CHECK_IF_FCBOPEN_WORK_INTERVAL', 5, 'seconds, Waiting time for check if open fcb let uf back to normal' FROM DUAL
    UNION
    SELECT 'RESTORE_LAST_AREA', 1, 'Restoring last area automatically' FROM DUAL;
COMMIT;

--##PARAM
DELETE UFINPUT;
DELETE UFPARAM;
COMMIT;
INSERT INTO UFPARAM SELECT ROWNUM, NAME||'UF', SUBSTIDX, COLORCODE  FROM FEEDERPARAM WHERE FDTYPE = 1;
INSERT INTO UFINPUT SELECT IDX, 0, 0 FROM UFPARAM;
COMMIT;
--##INPUT
DELETE INPUTXREF2;
INSERT INTO INPUTXREF2 SELECT DR.TABLENAME||'INPUT', DR.COLNAME, FP.IDX, 1, 1, DR.STATION, DR.CATEGORY, DR.POINT, DR.ATTRIBUTE, DR.DESCRIPT FROM UFPARAM FP, DAS_RTDB DR WHERE FP.NAME = DR.EQUIP_NUM;
INSERT INTO INPUTXREF2 SELECT DR.TABLENAME||'INPUT', DR.COLNAME, FP.IDX, 1, DR.RTDBTYPE, DR.STATION, DR.CATEGORY, DR.POINT, DR.ATTRIBUTE, DR.DESCRIPT FROM FEEDERPARAM2 FP, DAS_RTDB DR WHERE FP.NAME = DR.EQUIP_NUM AND DR.TABLENAME = 'FEEDER' AND DR.COLNAME = 'LSGROUPLOCKFLAG';
INSERT INTO INPUTXREF2 SELECT DR.TABLENAME||'INPUT', DR.COLNAME, FP.IDX, 1, DR.RTDBTYPE, DR.STATION, DR.CATEGORY, DR.POINT, DR.ATTRIBUTE, DR.DESCRIPT FROM FEEDERPARAM2 FP, DAS_RTDB DR WHERE FP.NAME = DR.EQUIP_NUM AND DR.TABLENAME = 'FEEDER' AND DR.COLNAME = 'LSACT';
INSERT INTO INPUTXREF2 SELECT DR.TABLENAME||'INPUT', DR.COLNAME, FP.IDX, 1, DR.RTDBTYPE, DR.STATION, DR.CATEGORY, DR.POINT, DR.ATTRIBUTE, DR.DESCRIPT FROM FEEDERPARAM2 FP, DAS_RTDB DR WHERE FP.NAME = DR.EQUIP_NUM AND DR.TABLENAME = 'FEEDER' AND DR.COLNAME = 'LSLOCKFLAG';
COMMIT;


EXIT;


EXIT;
