-- ## WORKAROUND
DROP TABLE FEEDERPARAM2;
CREATE TABLE FEEDERPARAM2 AS SELECT * FROM FEEDERPARAM WHERE FDTYPE = 0;
ALTER TABLE FEEDERPARAM2 ADD (LSSCOPEIDX NUMBER DEFAULT 0);
ALTER TABLE FEEDERPARAM2 ADD (LSFEEDER_PRIORITY NUMBER);
ALTER TABLE FEEDERPARAM2 ADD (LSFDIDX NUMBER);
DROP TABLE FEEDERINPUT2;
CREATE TABLE FEEDERINPUT2 AS SELECT IDX FROM FEEDERINPUT;
ALTER TABLE FEEDERINPUT2 ADD (LSGROUPLOCKFLAG NUMBER DEFAULT 1);
ALTER TABLE FEEDERINPUT2 ADD (LSACT NUMBER DEFAULT 0);
ALTER TABLE FEEDERINPUT2 ADD (LSLOCKFLAG NUMBER DEFAULT 0);
DROP TABLE INPUTXREF2;
CREATE TABLE INPUTXREF2 AS SELECT * FROM INPUTXREF WHERE STATION = -999;


--## Need Dr.Yan's help ##--
-- ALTER TABLE FEEDERPARAM DROP COLUMN LSSCOPEIDX;
-- ALTER TABLE FEEDERPARAM DROP COLUMN LSFEEDER_PRIORITY;
-- ALTER TABLE FEEDERPARAM DROP COLUMN LSFDIDX;
-- ALTER TABLE FEEDERINPUT DROP COLUMN LSGROUPLOCKFLAG;
-- ALTER TABLE FEEDERINPUT DROP COLUMN LSACT;
-- ALTER TABLE FEEDERPARAM ADD (LSSCOPEIDX NUMBER INVISIBLE DEFAULT 0);
-- ALTER TABLE FEEDERPARAM ADD (LSFEEDER_PRIORITY NUMBER INVISIBLE);
-- ALTER TABLE FEEDERPARAM ADD (LSFDIDX NUMBER INVISIBLE);
-- ALTER TABLE FEEDERINPUT ADD (LSGROUPLOCKFLAG NUMBER INVISIBLE DEFAULT 1);
-- ALTER TABLE FEEDERINPUT ADD (LSACT NUMBER INVISIBLE DEFAULT 0);

DROP TABLE LSSCOPEPARAM;
CREATE TABLE LSSCOPEPARAM (
    IDX         NUMBER PRIMARY KEY,
    GROUPNAME   VARCHAR2(19),
    CONSTRAINT  UNI_GROUPNAME   UNIQUE(GROUPNAME)
);



DROP TABLE LS_CONFIGURATION;
CREATE TABLE LS_CONFIGURATION (
    NAME             VARCHAR2(63)       NOT NULL,
    VALUE            NUMBER     NOT NULL,
    COMMENTS          VARCHAR2(255)      NOT NULL,
    CONSTRAINT  UNIPARAMETRY   UNIQUE(NAME)
);

DROP TABLE UFINPUT;
DROP TABLE UFPARAM;

CREATE TABLE UFPARAM(
    IDX           NUMBER(6) PRIMARY KEY,
    NAME          VARCHAR2(63),
    SUBSTIDX      NUMBER(6) NOT NULL,
    COLORCODE     NUMBER
);

CREATE TABLE UFINPUT(
    IDX           NUMBER(6) NOT NULL,
    STASTATUS     NUMBER(1),
    LOCKFLAG      NUMBER(1),
    FOREIGN KEY (IDX) REFERENCES UFPARAM  (IDX)
);




CREATE OR REPLACE VIEW VIEW_UF_CFG AS
SELECT UP.NAME
       , UP.COLORCODE
       , STASTATUS.STATION STATION_STASTATUS
       , STASTATUS.CATEGORY CATEGORY_STASTATUS
       , STASTATUS.POINT POINT_STASTATUS
       , STASTATUS.RTDBTYPE RTDBTYPE_STASTATUS
       , STASTATUS.ATTRIBUTE ATTRIBUTE_STASTATUS
       , LOCKFLAG.STATION STATION_LOCKFLAG
       , LOCKFLAG.CATEGORY CATEGORY_LOCKFLAG
       , LOCKFLAG.POINT POINT_LOCKFLAG
       , LOCKFLAG.RTDBTYPE RTDBTYPE_LOCKFLAG
       , LOCKFLAG.ATTRIBUTE ATTRIBUTE_LOCKFLAG
FROM UFPARAM UP
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF2 IX WHERE IX.TABLENAME = 'UFINPUT' AND IX.COLNAME = 'STASTATUS') STASTATUS
ON (UP.IDX = STASTATUS.KEYIDX)
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF2 IX WHERE IX.TABLENAME = 'UFINPUT' AND IX.COLNAME = 'LOCKFLAG') LOCKFLAG
ON (UP.IDX = LOCKFLAG.KEYIDX);


CREATE OR REPLACE VIEW VIEW_LS_CFG AS
SELECT 
       SCOPE.GROUPNAME
       , LSGROUPLOCKFLAG.STATION STATION_LSGROUPLOCKFLAG
       , LSGROUPLOCKFLAG.CATEGORY CATEGORY_LSGROUPLOCKFLAG
       , LSGROUPLOCKFLAG.POINT POINT_LSGROUPLOCKFLAG
       , LSGROUPLOCKFLAG.RTDBTYPE RTDBTYPE_LSGROUPLOCKFLAG
       , LSGROUPLOCKFLAG.ATTRIBUTE ATTRIBUTE_LSGROUPLOCKFLAG
       , SUB.NAME SUBSTATION
       , FP.LSFEEDER_PRIORITY
       , FP.LSFDIDX
       , FP.NAME FEEDER
       , FP.FDTYPE FDTYPE
       , LSACT.STATION STATION_LSACT
       , LSACT.CATEGORY CATEGORY_LSACT
       , LSACT.POINT POINT_LSACT
       , LSACT.RTDBTYPE RTDBTYPE_LSACT
       , LSACT.ATTRIBUTE ATTRIBUTE_LSACT
       , UPLINECOLORCODE.STATION STATION_UPLINECOLORCODE
       , UPLINECOLORCODE.CATEGORY CATEGORY_UPLINECOLORCODE
       , UPLINECOLORCODE.POINT POINT_UPLINECOLORCODE
       , UPLINECOLORCODE.RTDBTYPE RTDBTYPE_UPLINECOLORCODE
       , UPLINECOLORCODE.ATTRIBUTE ATTRIBUTE_UPLINECOLORCODE
       , STASTATUS.STATION STATION_STASTATUS
       , STASTATUS.CATEGORY CATEGORY_STASTATUS
       , STASTATUS.POINT POINT_STASTATUS
       , STASTATUS.RTDBTYPE RTDBTYPE_STASTATUS
       , STASTATUS.ATTRIBUTE ATTRIBUTE_STASTATUS
       , CTRL.CTRLSTATION
       , CTRL.CTRLRECORD
       , LOCKFLAG.STATION STATION_LSLOCKFLAG
       , LOCKFLAG.CATEGORY CATEGORY_LSLOCKFLAG
       , LOCKFLAG.POINT POINT_LSLOCKFLAG
       , LOCKFLAG.RTDBTYPE RTDBTYPE_LSLOCKFLAG
       , LOCKFLAG.ATTRIBUTE ATTRIBUTE_LSLOCKFLAG
       , PA.STATION   STATION_PA
       , PA.CATEGORY  CATEGORY_PA
       , PA.POINT     POINT_PA
       , PA.RTDBTYPE  RTDBTYPE_PA
       , PA.ATTRIBUTE ATTRIBUTE_PA
       , PB.STATION   STATION_PB
       , PB.CATEGORY  CATEGORY_PB
       , PB.POINT     POINT_PB
       , PB.RTDBTYPE  RTDBTYPE_PB
       , PB.ATTRIBUTE ATTRIBUTE_PB
       , PC.STATION   STATION_PC
       , PC.CATEGORY  CATEGORY_PC
       , PC.POINT     POINT_PC
       , PC.RTDBTYPE  RTDBTYPE_PC
       , PC.ATTRIBUTE ATTRIBUTE_PC
FROM FEEDERPARAM2 FP
LEFT JOIN (SELECT IDX, GROUPNAME FROM LSSCOPEPARAM LP) SCOPE
ON (FP.LSSCOPEIDX = SCOPE.IDX)
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF2 IX WHERE IX.TABLENAME = 'FEEDERINPUT' AND IX.COLNAME = 'LSGROUPLOCKFLAG') LSGROUPLOCKFLAG
ON (FP.IDX = LSGROUPLOCKFLAG.KEYIDX)
LEFT JOIN (SELECT SX.IDX, SX.STATION, SX.CATEGORY, SX.POINT
            , DECODE(SX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, SX.ATTRIBUTE
            FROM SWTUPLINEXREF SX WHERE SX.IDX IN (SELECT BRKIDX FROM FEEDERPARAM2)) UPLINECOLORCODE
ON (FP.BRKIDX = UPLINECOLORCODE.IDX)
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF2 IX WHERE IX.TABLENAME = 'FEEDERINPUT' AND IX.COLNAME = 'LSACT') LSACT
ON (FP.IDX = LSACT.KEYIDX)
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF IX WHERE IX.TABLENAME = 'SWITCHINPUT' AND IX.COLNAME = 'STASTATUS' AND IX.KEYIDX IN (SELECT BRKIDX FROM FEEDERPARAM2)) STASTATUS
ON (FP.BRKIDX = STASTATUS.KEYIDX)
LEFT JOIN (SELECT CX.KEYIDX, CX.CTRLSTATION, CX.CTRLRECORD FROM CONTROLXREF CX 
           WHERE CX.TABLENAME = 'SWITCHOUTPUT' AND CX.COLNAME = 'STASTATUS' AND CX.KEYIDX IN (SELECT BRKIDX FROM FEEDERPARAM2)) CTRL
ON (FP.BRKIDX = CTRL.KEYIDX)
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF2 IX WHERE IX.TABLENAME = 'FEEDERINPUT' AND IX.COLNAME = 'LSLOCKFLAG') LOCKFLAG
ON (FP.IDX = LOCKFLAG.KEYIDX)
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF IX WHERE IX.TABLENAME = 'SWITCHINPUT' AND IX.COLNAME = 'PA' AND IX.KEYIDX IN (SELECT BRKIDX FROM FEEDERPARAM2)) PA
ON (FP.BRKIDX = PA.KEYIDX)
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF IX WHERE IX.TABLENAME = 'SWITCHINPUT' AND IX.COLNAME = 'PB' AND IX.KEYIDX IN (SELECT BRKIDX FROM FEEDERPARAM2)) PB
ON (FP.BRKIDX = PB.KEYIDX)
LEFT JOIN (SELECT IX.KEYIDX, IX.STATION, IX.CATEGORY, IX.POINT
            , DECODE(IX.RTDBTYPE,1,'S',2,'T','S') RTDBTYPE, IX.ATTRIBUTE
            FROM INPUTXREF IX WHERE IX.TABLENAME = 'SWITCHINPUT' AND IX.COLNAME = 'PC' AND IX.KEYIDX IN (SELECT BRKIDX FROM FEEDERPARAM2)) PC
ON (FP.BRKIDX = PC.KEYIDX)
LEFT JOIN (SELECT SP.IDX, SP.NAME FROM SUBSTATIONPARAM SP WHERE SP.IDX IN (SELECT SUBSTIDX FROM FEEDERPARAM2)) SUB
ON (FP.SUBSTIDX = SUB.IDX);


EXIT;
